---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notebooks-backup-recover
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: notebooks-backup-recover
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "persistentvolumes"]
    verbs: ["get", "list", "watch", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: notebooks-backup-recover
subjects:
- kind: ServiceAccount
  name: notebooks-backup-recover
  namespace: default
roleRef:
  kind: ClusterRole
  name: notebooks-backup-recover
  apiGroup: rbac.authorization.k8s.io
