---
rbac:
  enabled: true

backup:
  schedule: 25 23 * * *
  args:
    - "--exclude=/exports/archived-*-pvc-*"
    - "--exclude=/exports/*-prom-prometheus-server-pvc-*"
    - "--exclude=/exports/prometheus-*-pvc-*"
  nfsPath: /exports
  repository:
  sshKey:
  knownHosts:
  env: {}

  #
  # Snapshots rotation in backup storage
  #
  # Parameters taken from backup:
  #
  #  * repository
  #  * sshKey
  #  * knownHosts
  #  * env
  #
  culler:
    # empty value to disable
    schedule: 20 21 * * 0
    # arguments for restic forget
    args:
      - "--keep-monthly"
      - "12"
      - "--keep-daily"
      - "30"
      - "--prune"

image:
  repository: registry.egi.eu/vo.notebooks.egi.eu/svc-backup
  tag: ""
  pullPolicy: IfNotPresent

nodeSelector:
  nfs-server: "true"

nodeSelectorCuller: {}

tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

affinity: {}
