backup:
  schedule: 25 23 * * * 
  repository: ""
  image:
    name: eginotebooks/svc-backup
    tag: '0.1.0'
    pullPolicy: IfNotPresent
  nfsPath: /exports

nodeSelector:
  nfs-server: "true"

toleratrions:
    key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
