apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: notebooks-backup
  labels:
    app: {{ template "notebook-backup.name" . }}
    chart: {{ template "notebook-backup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.backup.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.rbac.enabled }}
          serviceAccountName: notebooks-backup
          {{- end }}
          restartPolicy: Never
          containers:
          - name: backup
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["/usr/local/bin/backup.sh"]
            volumeMounts:
            - mountPath: /exports
              name: exports
            - mountPath: /root/.ssh/
              name: restic-ssh
            - mountPath: /restic-secret/
              name: restic-password
            env:
            - name: NFS_PATH
              value: /exports
            - name: RESTIC_REPOSITORY
              value: {{ .Values.backup.repository }}
            - name: RESTIC_PASSWORD_FILE
              value: /restic-secret/password
            resources:
{{ toYaml .Values.resources | indent 14 }}
          volumes:
          - hostPath:
              path: {{ .Values.backup.nfsPath }}
              type: DirectoryOrCreate
            name: exports
          - secret:
              secretName: restic-ssh
              defaultMode: 256
            name: restic-ssh
          - secret:
              secretName: restic-password
              defaultMode: 256
            name: restic-password
        {{- with .Values.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with .Values.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
        {{- end }}
