{{- if .Values.backup.culler.schedule }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: notebooks-backup-culler
  labels:
    app: {{ template "notebook-backup.name" . }}-culler
    chart: {{ template "notebook-backup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  concurrencyPolicy: Replace
  schedule: {{ .Values.backup.culler.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: backup-culler
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command:
              - restic
              - "-v"
              - forget
{{ toYaml .Values.backup.culler.args | indent 14 }}
            volumeMounts:
            {{- if .Values.backup.sshKey }}
            - mountPath: /root/.ssh/
              name: restic-ssh
            {{- end }}
            - mountPath: /restic-secret/
              name: restic-password
            env:
            - name: RESTIC_REPOSITORY
              value: {{ .Values.backup.repository }}
            - name: RESTIC_PASSWORD_FILE
              value: /restic-secret/password
{{- if .Values.backup.env }}
            envFrom:
            - secretRef:
                name: restic-env
{{- end }}
            resources:
{{ toYaml .Values.resources | indent 14 }}
          volumes:
          {{- if .Values.backup.sshKey }}
          - secret:
              secretName: restic-ssh
              defaultMode: 256
            name: restic-ssh
          {{- end }}
          - secret:
              secretName: restic-password
              defaultMode: 256
            name: restic-password
        {{- with .Values.nodeSelectorCuller }}
          nodeSelector:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with .Values.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
        {{- end }}
{{- end }}
