{{- if .Values.backup.sshKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: restic-ssh
  labels:
    app: {{ template "notebook-backup.name" . }}
    chart: {{ template "notebook-backup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  id_rsa: {{ .Values.backup.sshKey | b64enc | quote }}
  known_hosts: {{ .Values.backup.knownHosts | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: restic-password
  labels:
    app: {{ template "notebook-backup.name" . }}
    chart: {{ template "notebook-backup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.backup.password | b64enc | quote }}
{{- if .Values.backup.env }}
---
apiVersion: v1
kind: Secret
metadata:
  name: restic-env
type: Opaque
data:
{{- range $key, $val := .Values.backup.env }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}
