---
apiVersion: v1
kind: Secret
metadata:
  name: restic-ssh
  labels:
    app: {{ template "notebook-backup.name" . }}
    chart: {{ template "notebook-backup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  id_rsa: {{ .Values.backup.sshKey | b64enc | quote }}
  known_hosts.pem: {{ .Values.backup.knownHosts | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: restic-password
  labels:
    app: {{ template "notebook-backup.name" . }}
    chart: {{ template "notebook-backup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  passwd: {{ .Values.backup.password | b64enc | quote }}
