---
name: Create helm chart

on:
  push:
    # only pushes on master so we don't push intermediate results
    branches:
      - master
      # also when tagging so we get nice versioning
    tags:
      - "*"
  pull_request:

jobs:
  chart:
    name: Create chart
    runs-on: ubuntu-latest

    steps:
      - name: check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up python
        uses: actions/setup-python@v5
      - name: Install requirements
        run: |
          pip install -r dev-requirements.txt
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.17.3
      - name: Build chart
        run: |
          chartpress
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.event_name != 'pull_request'
      - uses: tibdex/github-app-token@v2
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
        if: github.event_name != 'pull_request'
      - name: Push chart
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git config --global user.name "egibot"
          git config --global user.email "egibot@egi.eu"
          chartpress --push --publish-chart
        if: github.event_name != 'pull_request'
